### ISSUE TITLE
[TEST] Upgrade the openSUSE image to 15.5, RKE1 & RKE2 versions to 1.27 in test CI

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1087]
## What's the test to develop? Please describe

Our test is set to run with rke1 & rke2 versions as 1.24 and the default value of image for guest cluster is 15.4. We need to update them.

openSUSE image - 15.5
K8s version - 1.27

**Comment by khushboo-rancher** [comment]
The test running on ECM is running with RKE1 v1.26.9-rancher1-1 and RKE2 v1.26.10+rke2r2. We can keep https://github.com/harvester/tests/blob/main/config.yml in sync with it.

**Comment by albinsun** [comment]
Ref. https://documentation.suse.com/sles/15-SP5/single-html/SLES-minimal-vm/index.html
![image](https://github.com/harvester/tests/assets/2773781/5ea57df0-32b5-4696-b745-5f0125d18f4d)

**Comment by albinsun** [comment]
Hit similiar issue https://github.com/rancher/rancher/issues/41650

```
...
Jan 30 15:08:00 myrke2-24-pool1-3e7f2660-c662x rancher-system-agent[1976]: time="2024-01-30T15:08:00Z" level=error msg="error while staging: all endpoint
s failed: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io: i/o timeout: failed to get image index.docker.io/rancher/system-agent-in
staller-rke2:v1.24.17-rke2r1"

Jan 30 15:08:00 myrke2-24-pool1-3e7f2660-c662x rancher-system-agent[1976]: time="2024-01-30T15:08:00Z" level=error msg="error executing instruction 0: all endpoints failed: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io: i/o timeout: failed to get image index.docker.io/rancher/system-agent-installer-rke2:v1.24.17-rke2r1"

Jan 30 15:08:01 myrke2-24-pool1-3e7f2660-c662x rancher-system-agent[1976]: time="2024-01-30T15:08:01Z" level=error msg="error loading x509 client cert/key for probe kube-apiserver (/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt//var/lib/rancher/rke2/server/tls/client-kube-apiserver.key): open /var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt: no such file or directory"
...
```

**Comment by albinsun** [comment]
```
myrke2c-pool1-d27f96e5-5r27g:/var/log # grep -v DEBUG cloud-init.log
2024-01-31 02:00:59,171 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/vda][dsmode=net]
2024-01-31 02:00:59,323 - stages.py[INFO]: Applying network configuration from fallback bringup=False: {'ethernets': {'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': 'a6:76:67:84:e7:d7'}}}, 'version': 2}
{'type': 'physical', 'name': 'eth0', 'mac_address': 'a6:76:67:84:e7:d7', 'match': {'macaddress': 'a6:76:67:84:e7:d7'}, 'subnets': [{'type': 'dhcp4'}]}
{'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': 'a6:76:67:84:e7:d7'}}}
2024-01-31 02:01:05,158 - stages.py[INFO]: Skipping modules 'ca-certs' because they are not verified on distro 'sles'.  To run anyway, add them to 'unverified_modules' in config.
2024-01-31 02:01:05,619 - cc_growpart.py[INFO]: '/' resized: changed (/dev/vdb, 3) from 838843904 to 42911907328
2024-01-31 02:01:06,489 - stages.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'sles'.  To run anyway, add them to 'unverified_modules' in config.
```

**Comment by albinsun** [comment]
## Symptoms
1. Stuck at updating
   ![image](https://github.com/harvester/tests/assets/2773781/a7a52be9-c9da-45f7-9aea-d7b29cdedede)
1. secret received was too old
    `journalctl -u rancher-system-agent.service --follow`
    ```
    Feb 01 17:40:22 myrke2-sles15-pool1-2443a795-wb57d rancher-system-agent[1958]: time="2024-02-01T17:40:22Z" level=error msg="error syncing 'fleet-default/myrke2-sles15-bootstrap-template-wfpnj-machine-plan': handler secret-watch: secret received was too old, requeuing"
    Feb 01 17:40:27 myrke2-sles15-pool1-2443a795-wb57d rancher-system-agent[1958]: time="2024-02-01T17:40:27Z" level=info msg="[K8s] updated plan secret fleet-default/myrke2-sles15-bootstrap-template-wfpnj-machine-plan with feedback"
    Feb 01 17:40:27 myrke2-sles15-pool1-2443a795-wb57d rancher-system-agent[1958]: time="2024-02-01T17:40:27Z" level=error msg="[K8s] received secret to process that was older than the last secret operated on. (33095805 vs 33095877)"
    Feb 01 17:40:27 myrke2-sles15-pool1-2443a795-wb57d rancher-system-agent[1958]: time="2024-02-01T17:40:27Z" level=error msg="error syncing 'fleet-default/myrke2-sles15-bootstrap-template-wfpnj-machine-plan': handler secret-watch: secret received was too old, requeuing"
    
    ```
    :hammer: Try to rotate certificate and restart rke2-server
    <details>    
    ```
    myrke2-sles15-pool1-2443a795-wb57d:/var/log # rke2 certificate rotate
    INFO[0003] Server detected, rotating server certificates 
    INFO[0003] Rotating certificates for admin service      
    INFO[0003] Rotating certificates for etcd service       
    INFO[0003] Rotating certificates for api-server service 
    INFO[0003] Rotating certificates for controller-manager service 
    INFO[0003] Rotating certificates for cloud-controller service 
    INFO[0003] Rotating certificates for scheduler service  
    INFO[0003] Rotating certificates for rke2-server service 
    INFO[0003] Rotating dynamic listener certificate        
    INFO[0003] Rotating certificates for rke2-controller service 
    INFO[0003] Rotating certificates for auth-proxy service 
    INFO[0003] Rotating certificates for kubelet service    
    INFO[0003] Rotating certificates for kube-proxy service 
    INFO[0003] Successfully backed up certificates for all services to path /var/lib/rancher/rke2/server/tls-1706809339, please restart rke2 server or agent to rotate certificates 
    ```
    </summary>


1. Fail syncing `etcd-endpoints://0xc0008cb340/127.0.0.1:237`, `context deadline exceeded`
    `journalctl -u rke2-server.service --follow`
    ```
    Feb 01 17:46:50 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"warn","ts":"2024-02-01T17:46:50.588559Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0008cb340/10.84.99.161:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
    Feb 01 17:46:50 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: time="2024-02-01T17:46:50Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
    Feb 01 17:46:54 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"warn","ts":"2024-02-01T17:46:54.465424Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0008cb340/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
    Feb 01 17:46:54 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"info","ts":"2024-02-01T17:46:54.466753Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
    Feb 01 17:47:05 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"warn","ts":"2024-02-01T17:47:05.591217Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0008cb340/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
    Feb 01 17:47:05 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: time="2024-02-01T17:47:05Z" level=error msg="Failed to get etcd members for learner management: context deadline exceeded"
    Feb 01 17:47:19 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"warn","ts":"2024-02-01T17:47:19.722532Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0008cb340/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
    Feb 01 17:47:19 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"info","ts":"2024-02-01T17:47:19.723051Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
    Feb 01 17:47:20 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: {"level":"warn","ts":"2024-02-01T17:47:20.595938Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0008cb340/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
    Feb 01 17:47:20 myrke2-sles15-pool1-2443a795-wb57d rke2[19513]: time="2024-02-01T17:47:20Z" level=error msg="Failed to get recorded learner progress from etcd: context deadline exceeded"
    ...
    ```

## Similar Issues
1. [RKE2 fails if docker is installed and running on the host on which the RKE2 nodes are running.](https://github.com/rancher/rke2/issues/4472#top)
#4472
2. [Issue running cluster-reset on v1.26 releases](https://github.com/rancher/rke2/issues/4052#top)
#4052
3. [rke2-server failing to start; no static pods](https://github.com/rancher/rke2/issues/2080#top)
#2080

**Comment by albinsun** [comment]
Provide test result on `harvester-v1.3.1-rc1` + `rancher-v2.7.9`.

Hit 2 issues:
1. Load balancer status
2. RKE2 cluster scale down (known issue)

Please refer following for detail.


## Environment
* Harvester
  * Version: `v1.3.1-rc1`
  * Profile: QEMU/KVM, single nodes (48C/128G/2T)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.9`
  * Profile: rancher-vcluster
  * RKE2 Version: `v1.26.11+rke2r1`


## Steps 
1. Import Harvester to Rancher and create cloud credential
   * <details>
     <summary> Harvester is Active :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/tests/assets/2773781/8033e356-9d75-429f-9f00-194f9084473c)
     </details>
  
  
1. Create RKE2 cluster
   * <details>
     <summary> Using image <b>sles15-sp5-minimal-vm.x86_64-cloud-gm.qcow2</b>
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/5c61a5a2-278f-4808-833a-22cfcb3e492d)
     </details>
     
   * <details>
     <summary> Customize cloud-config for SLES registration code
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/eaf31d35-b029-4164-80e6-95ad19a6ac28)
     </details>

   * <details>
     <summary> RKE2 <code>v1.26.11+rke2r1</code> with Harvester cloud provider
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/d593cae5-365e-42dc-b82c-afac7d115d75)
     </details>

1. Check RKE2 cluster status
   * <details>
     <summary> Cluster is <code>Active</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/dd1e2735-ba65-4e87-bb60-1fcb9be6074b)
     </details>

   * <details>
     <summary> <b>harvester-cloud-provider</b> and <b>harvester-csi-driver</b> are deployed :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/7a6be06b-9b5b-43cb-b0aa-4476b87028c0)
     </details>

1. Deploy Nginx workload with pvc mount
   * <details>
     <summary> Use image <code>nginx:latest</code>
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/94ecfbcb-875e-4d24-bd57-664909140c28)
     </details>
     
   * <details>
     <summary> Create PVC on-demand
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/52882e56-c923-4bcd-87fd-fb57e0cb6c76)
     </details>
     
   * <details>
     <summary> Mount to <b>/data</b>
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/cd2ab034-8cf4-4b26-b7e7-861aba2ac3aa)
     </details>

   * <details>
     <summary> Deployment is Active and PVC does mount
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/901746c1-e609-4ae9-b2af-dceaeed2dd56)
     </details>


1. Deploy Load-Balancer Service for Nginx deployment
   * <details>
     <summary> Status is <code>Active</code> :x:
     </summary>

     Shows <code>Pending</code>
     ![image](https://github.com/harvester/tests/assets/2773781/daa3ec6a-705a-476a-9453-79304da0dbda)
     ![image](https://github.com/harvester/tests/assets/2773781/0ade4a1c-d5b0-4c5e-89ca-c709a7ba28df)
     </details>


   * <details>
     <summary> Can access target nginx :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/e395a2f7-020b-486c-8f61-dfb17f7659a4)
     </details>

1. Scaling
   * <details>
     <summary> Scale Up :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/e3717597-1240-49cd-8ccd-d9a5c3771102)
     Deployment and LB still works
     ![image](https://github.com/harvester/tests/assets/2773781/d6c66c78-a77d-4fdb-8d84-729172a365e0)
     ![image](https://github.com/harvester/tests/assets/2773781/35047a74-e94c-4cd0-8764-8884f431f522)
     </details>
     
   * <details>
     <summary> Scale Down :x: harvester/harvester/issues/4358
     </summary>
    
     ![image](https://github.com/harvester/tests/assets/2773781/05c26b02-d389-44d3-a19f-6b0ee7f61720)
     ~Deployment and LB still works~
     </details>


## Supportbundle
[supportbundle_sles15_2024-02-02T11-40-15Z.zip](https://github.com/harvester/tests/files/14139509/supportbundle_sles15_2024-02-02T11-40-15Z.zip)

**Comment by albinsun** [comment]
Provide comparism between openSUSE Leap `15.3` and `15.5`, they give identical test result, will send PR to bump `opensuse-image-url` to `15.5`.


# openSUSE-15.5 Verification

Currently fixture `image_opensuse` are used by following test suites:
1. _test_1_images.py_
2. _test_3_vm_functions.py_
3. _test_4_vm_backup_restore.py_
4. _test_4_vm_snapshot.py_
5. _test_5_vm_networks.py_
6. _test_5_vm_networks_interact.py_
7. _test_z_terraform.py_

Ref. https://github.com/search?q=repo%3Aharvester%2Ftests%20image_opensuse&type=code



## Compare test run based on openSUSE-15.3 and-15.5
* Harvester: `v1.2.2-dev-20240329`
* Test cases result statistics should be the same.

1. :green_circle: _test_1_images.py_

   * <details>
     <summary> openSUSE-15.3: 6 Passed, 0 failed
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/4cb47de2-0b94-4e14-848d-b97299c3b930)
     <details>

   * <details>
     <summary> openSUSE-15.5: 6 Passed, 0 failed
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/75eff364-dfe0-498b-87f0-5db97b668058)
     <details>

1. :green_circle: _test_3_vm_functions.py_

   * <details>
     <summary> openSUSE-15.3: 30 Passed, 2 failed (<code>test_update_vm_machine_type[q35_to_pc, pc_to_q35]</code>)
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/16c2aea2-24e0-4b80-8970-f1be0e8e0079)
     <details>

   * <details>
     <summary> openSUSE-15.5: 30 Passed, 2 failed (<code>test_update_vm_machine_type[q35_to_pc, pc_to_q35]</code>)
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/62099f80-eec1-46dc-af2f-d952911c9bcc)
     <details>

1. :green_circle: _test_4_vm_backup_restore.py_

   * <details>
     <summary> openSUSE-15.3: 20 Passed, 2 failed (<code>test_restore_replace_with_delete_vols[S3, NFS]</code>)
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/7d926844-c919-479d-ac27-babaa5ea7926)
     <details>

   * <details>
     <summary> openSUSE-15.5: 20 Passed, 2 failed (<code>test_restore_replace_with_delete_vols[S3, NFS]</code>)
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/0c2a5986-6f64-452c-bdb3-e1f8fcdaadcc)
     <details>

1. :green_circle: _test_4_vm_snapshot.py_

   * <details>
     <summary> openSUSE-15.3: 8 Passed
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/8429e0c4-d229-46a0-ae85-5a923dd9e2ce)
     <details>

   * <details>
     <summary> openSUSE-15.5: 8 Passed
     </summary>

     ![image](https://github.com/harvester/tests/assets/2773781/1af92918-0984-4b22-86c4-31745eb53cee)
     <details>

1. :green_circle: _test_5_vm_networks.py_
   > Fail too on daily test env.

   * <details>
     <summary> openSUSE-15.3: 1 skipped, 2 errors (<code>test_add_vlan</code>, <code>test_vms_on_same_vlan</code>: <code>VM network created but route info not available</code>)
     </summary>

     <details>

   * <details>
     <summary> openSUSE-15.5: 1 skipped, 2 errors (<code>test_add_vlan</code>, <code>test_vms_on_same_vlan</code>: <code>VM network created but route info not available</code>)
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/d7ed8806-9297-42e5-91d1-6069a5580a8c)
     <details>

1. :green_circle: _test_5_vm_networks_interact.py_

   * <details>
     <summary> openSUSE-15.3: 1 Passed, 4 errors (<code>test_vlan_network_connection</code>, <code>test_mgmt_to_vlan_connection</code>, <code>test_vlan_to_mgmt_connection</code>, <code>test_delete_vlan_from_multiple</code>: <code>VM network created but route info not available</code>)
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/7fbb0004-a25d-4cd3-b898-525f3d22fae3)
     <details>

   * <details>
     <summary> openSUSE-15.5: 1 Passed, 4 errors (<code>test_vlan_network_connection</code>, <code>test_mgmt_to_vlan_connection</code>, <code>test_vlan_to_mgmt_connection</code>, <code>test_delete_vlan_from_multiple</code>: <code>VM network created but route info not available</code>)
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/3e4df5cd-c6c0-4206-9efe-4ed77e71add3)
     <details>

1. :green_circle: _test_z_terraform.py_

   * <details>
     <summary> openSUSE-15.3: 13 Passed
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/0bbdd50e-e0f0-4ed2-ac9f-6b90317d005d)
     <details>

   * <details>
     <summary> openSUSE-15.5: 13Passed
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/188b7cdd-87e4-4e99-8834-72a445dccbba)
     <details>

**Comment by albinsun** [comment]
Close as PRs already merged.
