### ISSUE TITLE
[TEST] OpenSuse and ubuntu image versions should be pulled from config.yaml in the upgrade test

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1209]
## What's the test to develop? Please describe

OpenSuse, Ubuntu and any other OS versions in the upgrade test should come from config file rather than be hardcoded.

e.g. - https://github.com/harvester/tests/blob/main/harvester_e2e_tests/integrations/test_upgrade.py#L520

**Comment by lanfon72** [comment]
Close as this has been done in #1188
