### ISSUE TITLE
[TEST]  Consider upgrade Rancher in daily test env. to v2.8.3+  

### ISSUE THREAD

**Issue by albinsun** [harvester/tests#1271]
## What's the test to develop? Please describe

In current daily env. we use `rancher-v2.8.1`.
However, there is a block issue in `v2.8.0`~`v2.8.2` wihch may cause RKE2 cluster provision fail.

[Resolved - [BUG] All pools unavailable on RKE2/K3s provisioned clusters on Rancher 2.8.0-2.8.2](https://github.com/rancher/rancher/issues/44929#top)

As it's fixed in `v2.8.3`, so we better having an upgrade.

## Prerequisite and dependency of test

Test case `integrations/test_9_rancher_integration.py::TestRKE2::test_create_rke2`
![image](https://github.com/harvester/tests/assets/2773781/406c0942-5132-439d-9a1a-7a9cd29b4c3f)

## Describe the items of the test development (DoD, definition of done) you'd like
Upgrade daily test env.'s Rancher to `v2.8.3`

## Additional context
n/a

**Comment by albinsun** [comment]
![image](https://github.com/harvester/tests/assets/2773781/b12fb8d9-08e3-4bf3-8f18-d398fde605c7)

**Comment by khushboo-rancher** [comment]
@albinsun Sounds good.

**Comment by albinsun** [comment]
Upgrade to `v2.8.3` done.
![image](https://github.com/harvester/tests/assets/2773781/d795757c-ed64-4863-b555-112079821210)

Verification in `harvester-runtests#14`
![image](https://github.com/harvester/tests/assets/2773781/e7860fd7-bff5-41f9-8995-85eeb7a8715e)
