### ISSUE TITLE
[TEST] Schedule e2e and upgrade test run everyday on 1.3-head also.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1283]
## What's the test to develop? Please describe

Currently, e2e and upgrade test run on 1.2-head and master-head. Need to configure 1.3-head as well.

E2e & upgrade test should run on all branches everyday 1.2-head, 1.3-head and master-head

**Comment by khushboo-rancher** [comment]
@lanfon72 I don't see e2e and upgrade test running on 1.3

**Comment by lanfon72** [comment]
> @lanfon72 I don't see e2e and upgrade test running on 1.3

![image](https://github.com/harvester/tests/assets/5169694/8333270e-9dce-4d97-a1d0-b1fce591d4f1) ？

Daily e2e needs at least 8 hrs to run and we encountered stuck issue last week so only master had executed.

**Comment by lanfon72** [comment]
Checked that daily e2e will fail after master build, fixed.

**Comment by khushboo-rancher** [comment]
The e2e test is running on 1.2-head, master and 1.3-head now
