### ISSUE TITLE
[TEST] Enhance cypress Jenkins test report link and test summary information 

### ISSUE THREAD

**Issue by TachunLin** [harvester/tests#1293]
### What's the test to develop? Please describe
Try to enhance the existing cypress test pipe to provide more test result information to better check the status and troubleshotting

### Describe the items of the test development

- [ ] Add new information to the slack message notification when cypress test started

  - Harvester version:
  - Rancher version:

- [ ] Add new information to the slack message when cypress test execution complete

  - Harvester version:
  - Rancher version:
  - Harvester VIP: (Easier to check the Harvester environment)
  - Rancher IP: (Easier to check the Harvester environment)
  - Report Link: (Click to open the cypress test report)

- [ ] Add the test summary message to the Jenkins job console page, thus user can directly access the required information

### Additional Context
Related PR: https://github.com/harvester/harvester-baremetal-ansible/pull/45

**Comment by khushboo-rancher** [comment]
@TachunLin Could you please check if this is resolved already?

**Comment by TachunLin** [comment]
This test tasks have been done and the related PR have been merged. Close this issue.
