### ISSUE TITLE
[TEST] Don't allow bot to close test issue on PR merge

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1296]
## What's the test to develop? Please describe

Right now, the bot closes the issue if a linked PR is merged. Could we change this behavior and rather close issue manually.
We might miss tracking important issue if a PR doesn't solve problem and issue get closed.

**Comment by irishgordo** [comment]
Perhaps we can close this out as this just has to deal with the git commits @khushboo-rancher ?
We just need to ensure that git commits don't use one of the following, referencing the [e2e] issue built:
```
    fix #xxx
    fixes #xxx
    fixed #xxx
    close #xxx
    closes #xxx
    closed #xxx
    resolve #xxx
    resolves #xxx
    resolved #xxx
```
Where `#xxx` can be either the "https-link" or "issue-id".
x-ref: https://github.blog/2013-01-22-closing-issues-via-commit-messages/

Where instead if we want to reference the [e2e] issue and not close it out we could do something like:
```
See also: issue-id-or-https-link-to-issue
Related issues: issue-id-or-https-link-to-issue
```
Or some other variant?
