### ISSUE TITLE
[TEST] Add test case to verify VM is migrated successfully during upgrade

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1357]
## What's the test to develop? Please describe

Add test case to verify VM is migrated successfully during upgrade

Context:
https://github.com/harvester/tests/issues/1097

**Comment by lanfon72** [comment]
I think we already covered the case in `verify_vms` to make sure VMs are keep in running (which means they had been migrated to upgraded node).
https://github.com/harvester/tests/blob/4059bc64520faffdcec641e40f6d8716a790ae31/harvester_e2e_tests/integrations/test_upgrade.py#L816-L821


If the issues is requesting another case, could you add test scenario and criteria?

**Comment by khushboo-rancher** [comment]
This ticket was created to ensure that the VM migration is tested during upgrade. Closing this.
