### ISSUE TITLE
[TEST] Test Rancher 2.9.0, 2.8.5, 2.7.14 with Harvester 1.3.1

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1441]
## What's the test to develop? Please describe

Run the Rancher integration test with Rancher different versions so that we can update the official support matrix.
Let's run the Rancher integration pipeline to achieve this.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Rancher 2.9.0 with RKE2 1.29
- [x] Rancher 2.8.5 with Rke2 1.28
- [x] Rancher 2.7.14 with Rke2 1.27 & 1.28 (If avaialble)

**Comment by m-ildefons** [comment]
| Rancher / RKE2 Version         | Result                 | Test Report |
| ------------------------------ | ---------------------- | ----------- |
| Rancher v2.9.0 and RKE2 v1.29  | :green_circle: SUCCESS | [Test Report](https://github.com/user-attachments/files/16675071/Harvester_20and_20Rancher_20Integration_20Tests.zip) |
| Rancher v2.8.5 and RKE2 v1.28  | | |
| Rancher v2.7.14 and RKE2 v1.27 | | |
| Rancher v2.7.14 and RKE2 v1.28 | | |

**Comment by khushboo-rancher** [comment]
I see there are failures related to the terraform in Rancher 2.7.14, terraform version might be the issue.

**Comment by khushboo-rancher** [comment]
I validated the failed cases manually, those worked fine. Additionally, validated the upgrade from v2.7.13-> 2.7.14, 2.8.5->2.8.6.
