### ISSUE TITLE
[BUG]  Diagnose & Fix `harvester_upgrade_test.groovy` for v1.3.2 Release

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#1451]
## Problem
- currently [harvester_upgrade_test.groovy](https://github.com/harvester/harvester-baremetal-ansible/blob/master/jenkins/harvester_upgrade_test.groovy) has been failing

## Information
On production Jenkins.

- **3 Jenkins Runs [229, 231, 232]**:
  -  all seem to be failing due to Cyclops Cluster provisioning issues -> unsure if this symptom can be addressed, it might possibly require a SPIKE/Investigation ticket
-  **2 Jenkins Runs [228, 233]:** 
    - seem to have failed complaining about `k8s_version` not being defined, this seems to have been addressed already in fined, but it absolutely looks defined in master on [harvester_upgrade_test.groovy](https://github.com/harvester/harvester-baremetal-ansible/blob/master/jenkins/harvester_upgrade_test.groovy), as [PR-37](https://github.com/harvester/harvester-baremetal-ansible/pull/37) was merged back in April 23rd, so maybe that error message is a "red herring"
 - **1 Jenkins Run [230]**:
     - seems to have failed due to networking issues with: `usr/bin/git clone --origin origin https://github.com/harvester/tests /tmp/upgrade_test-230-sr1d1pbj/tests`, this too may not be a symptom that be addressed, and it may have been related to underlying networking infrastructure
- **1 Jenkins Run [228]:**
    - seems to have failed on the `wait until cluster is ready` with the `configure_harvester_seeder` Ansible role running

**Comment by irishgordo** [comment]
@harvester/qa

**Comment by lanfon72** [comment]
close as this has been fixed, we `upgrade_test` running smoothly for a week.
