### ISSUE TITLE
[TASK] Create videos for Rancher integration demo

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/tests#1521]
This is created to track working on creating some videos to use in a Rancher knowledge sharing demo.

# Parts of Demo

## Overview of Harvester
- [ ]  Deploy Harvester Cluster

- [ ] UI

- [x] Image Creation

- [ ] Network Creation

- [x] VM Creation

- [x] Little bit of Debugging

## Integration with Rancher
- [x] How we connect Rancher & Harvester

- [x] Create RKE1/RKE2 cluster using Harvester node driver

- [x] RBAC

- [ ] vCluster Rancher

## Automation on Harvester cluster
- [x] Use Harvester APIs to create VMs on Harvester

- [x] Use RKE2 terraform to create rke2 cluster using Harvester VMs

**Comment by irishgordo** [comment]
Mostly all there :smile: for Automation Side/Demos/Media/Pictures/Videos/Links/Resources/small-helper-docs:
https://github.com/irishgordo/rancher-harvester-demo
