### ISSUE TITLE
[TEST] Test Rancher 2.9.2 & 2.8.8 with Harvester 1.3.2

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1541]
- [ ] Run Rancher CI with available k8s version with Rancher 2.9.2 & 2.8.8
- [ ] Test the upgrade path for  
         - [ ] Rancher 2.8.5 -> 2.9.2
         - [ ] Rancher 2.8.5 -> 2.8.8

**Comment by m-ildefons** [comment]
Rancher v2.8.5 isn't currently supported with Harvester v1.3.2
However Rancher v2.8.6 and Harvester v1.3.2 is a supported combination. Did you mean to run the upgrade tests with Rancher v2.8.6 instead?

**Comment by khushboo-rancher** [comment]
Sorry for the confusion I meant below upgrade path:
1. Rancher 2.8.5 + Harvester 1.3.1 -> Rancher 2.8.8 -> Harvester 1.3.2
2. Rancher 2.8.5 + Harvester 1.3.1 -> Rancher 2.9.2 -> Harvester 1.3.2

**Comment by m-ildefons** [comment]
### Harvester v1.3.2 x Rancher v2.8.8

| Test                                               | RKE 1 v1.27 | RKE 1 v1.28 | RKE 2 v1.27 | RKE 2 v1.28 |
| -------------------------------------------------- | --------- | --------- | --------- | --------- |
| Creating                                           | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Verifying the charts. Cloud provider, CSI driver   | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| Scale up (1 etc+cp, 1 wkr --> 1 etcd+cp, 3 wkr)    | | | | |
| Scale down (1 etcd+cp, 3 wkr --> 1 etcd+cp, 1 wkr) | | | | |
| Upgrading guest clusters                           | | N/A | | N/A |
| Deleting the clusters                              | :green_circle: | :green_circle: | :green_circle: | :green_circle: |

| Test                                                 | RKE 1 v1.27 | RKE 1 v1.28 | RKE 2 v1.27 | RKE 2 v1.28 |
| ---------------------------------------------------- | --------- | --------- | --------- | --------- |
| Upgrade Rancher v2.8.5 --> v2.8.8 (Harvester v1.3.1) | | | | |
| Upgrade Harvester v1.3.1 --> v1.3.2 (Rancher v2.8.8) | | | | |

### Harvester v1.3.2 x Rancher v2.9.2

| Test                                               | RKE 1 v1.27 | RKE 1 v1.28 | RKE 2 v1.27 | RKE 2 v1.28 |
| -------------------------------------------------- | --------- | --------- | --------- | --------- |
| Creating                                           | | | | |
| Verifying the charts. Cloud provider, CSI driver   | | | | |
| Scale up (1 etc+cp, 1 wkr --> 1 etcd+cp, 3 wkr)    | | | | |
| Scale down (1 etcd+cp, 3 wkr --> 1 etcd+cp, 1 wkr) | | | | |
| Upgrading guest clusters                           | | N/A | | N/A |
| Deleting the clusters                              | | | | |

| Test                                                 | RKE 1 v1.27 | RKE 1 v1.28 | RKE 2 v1.27 | RKE 2 v1.28 |
| ---------------------------------------------------- | --------- | --------- | --------- | --------- |
| Upgrade Rancher v2.8.5 --> v2.9.2 (Harvester v1.3.1) | | | | |
| Upgrade Harvester v1.3.1 --> v1.3.2 (Rancher v2.9.2) | | | | |

**Comment by khushboo-rancher** [comment]
>The upgrade from Harvester v1.3.1 to v1.3.2 also introduced a significant problem as all VMs were re-assgined new IPs, which broke the connection of the Rancher cluster agents. This resulted in all guest clusters becoming unavailable.

@m-ildefons Did you log an issue for this issue?

**Comment by m-ildefons** [comment]
Well... the IP addresses were re-assigned because I left the Harvester v1.3.1 --> v1.3.2 upgrade running over the weekend. Since I'm testing on a single node cluster, this upgrade causes the VMs to be shut down and since I left them over the weekend, the DHCP leases expired. Since I don't have control over the DHCP server in the test lab, I couldn't set up a MAC address map, to make the server always re-assign the same IP to the same client.
I'm using DHCP for IP address assignment in my test environment, since static IPs have a significantly worse user experience in Rancher.

I'll be re-running the upgrade test when I find some time and then make sure I don't leave the VMs shut off for a long time.

**Comment by khushboo-rancher** [comment]
Got it. For now, I think the test results are good enough. Running the upgrade won't be priority. We'll do it as a part of 1.4.0 release.

**Comment by khushboo-rancher** [comment]
Closing this as Rancher 2.9.2 & 2.8.8 are updated in the support matrix
