### ISSUE TITLE
[TEST] test_0_storage_network.py::test_storage_network failing on 1.4

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1566]
## What's the test to develop? Please describe

The test `test_0_storage_network.py::test_storage_network` failing on CI with 1.4-head

```
# teardown
        disable_spec = api_client.settings.StorageNetworkSpec.disable()
        code, data = api_client.settings.update('storage-network', disable_spec)
        assert 200 == code, (code, data)
        snet_disabled, (code, data) = setting_checker.wait_storage_net_disabled_on_harvester()
        assert snet_disabled, (code, data)
        snet_disabled, (code, data) = setting_checker.wait_storage_net_disabled_on_longhorn()
>       assert snet_disabled, (code, data)
E       AssertionError: ("No annotation 'k8s.v1.cni.cncf.io/network-status' on pod", {'apiVersion': 'v1', 'id': 'longhorn-system/instance-mana...'https://172.19.108.6/api/v1/namespaces/longhorn-system/pods/instance-manager-230bda33ca02e64a1b2e5a6e4cca5599'}, ...})
E       assert False

_          = (200,
 {'apiVersion': 'k8s.cni.cncf.io/v1', ...
```

**Additional related test cases failing:**
1. TestImageWithStorageNetwork::test_delete_image::teardown
2. TestVMWithStorageNetwork::test_enable_storage_network_with_api_stopped_vm::teardown
3. TestVMWithStorageNetwork::test_enable_storage_network_with_cli_stopped_vm::teardown

Additional context:
Why are other storage test cases are not failing like `TestImageWithStorageNetwork::test_create_image_by_file`, `TestImageWithStorageNetwork::test_download_image`, `TestImageWithStorageNetwork::test_delete_image`

**Comment by WebberHuang1118** [comment]
LH update annotation `k8s.v1.cni.cncf.io/networks` as Storage Network configured https://github.com/longhorn/longhorn-manager/blob/8fadbfbeb537ea8fbbc957b69e1e6b243cb806af/controller/backing_image_data_source_controller.go#L845-L853

LH manager doesn't rely on such annotation, if there is no annotation `k8s.v1.cni.cncf.io/network-status`, it directly retrieves pod IP by `pod.Status.PodIP`

**Comment by albinsun** [comment]
We will update our test logic as following
1. Check networks instead when enabling storage-network .
2. Should NOT have networks  when storage-netowrk is diabled.
