### ISSUE TITLE
[TEST] Test CSI chart bump to v0.1.21 in Rancher 2.8 branch

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1686]
## What's the test to develop? Please describe

This would be a manual effort to test the CSI chart latest version v0.1.21 on Rancher. The validation should be done with RKE1 cluster only

- [x] Deploy CSI latest version and verify the functionality of CSI chart.
        - [ ] Deploy a pvc with Harvester storage class
        - [ ] Attach to a workload, verify the volume attached in Longhorn.
        - [ ] Scale down to 0, verify the volume detached in Longhorn.
- [x] Uninstall the chart
- [x] Upgrade scenario
       - [ ] Deploy v0.1.18 CSI version
       - [ ] Deploy a pvc with Harvester storage class
        - [ ] Attach to a workload, verify the volume attached in Longhorn.
        - [ ] Scale down to 0, volume will fail to reattach
        - [ ] Upgrade CSI version to v0.1.21, attachment should work

**Comment by noahgildersleeve** [comment]
Validated with Harvester `v1.4.0` and Rancher `v2.8.10`. Tested with CSI driver `v0.1.21` and upgrade from `v0.1.18` -> `v0.1.21`. 
![Screenshot_20241209_201012](https://github.com/user-attachments/assets/42098846-859b-4671-bcb5-be75ea5b445f)
![Screenshot_20241209_200951](https://github.com/user-attachments/assets/94d020ba-e0b7-4c95-97db-188bb77c9310)
![Screenshot_20241209_200912](https://github.com/user-attachments/assets/0fbf551a-e27a-42c4-aefc-1c443917af80)
![Screenshot_20241209_200903](https://github.com/user-attachments/assets/a70c5a9b-2934-4235-80c7-f6c7ee7a9f3f)
![Screenshot_20241209_200818](https://github.com/user-attachments/assets/dfdf7746-8168-4064-b5a8-6af2d7bcde3a)
![Screenshot_20241209_200604](https://github.com/user-attachments/assets/4fdb2499-5abe-4019-b5f4-d02a2e394dcb)
![Screenshot_20241209_200550](https://github.com/user-attachments/assets/50c4f7c6-381e-4c47-91df-9c05563c15ae)
![Screenshot_20241209_200416](https://github.com/user-attachments/assets/cec4f581-5c5b-4520-866e-8ef3f613eaa9)
![Screenshot_20241209_200412](https://github.com/user-attachments/assets/5b4db65d-532a-47ae-bb23-ab545e522973)
![Screenshot_20241209_200330](https://github.com/user-attachments/assets/bd24e104-3c09-452c-84b6-d5f16236e74d)
![Screenshot_20241209_200323](https://github.com/user-attachments/assets/5ab1ad42-8efa-4c09-b4d9-1031c6f4c4a4)
![Screenshot_20241209_200313](https://github.com/user-attachments/assets/8e0556d3-f21f-4bd1-aec5-81dc7653fa88)
![Screenshot_20241209_200309](https://github.com/user-attachments/assets/21730eda-7477-4083-bf17-5ffa4e42188a)
![Screenshot_20241209_200247](https://github.com/user-attachments/assets/15bcb8be-f66f-4476-a021-945dcc637fe7)
![Screenshot_20241209_200016](https://github.com/user-attachments/assets/47ff4fd1-882c-4b7a-8a88-9053cbc418b7)
