### ISSUE TITLE
[DevOps] Test AirGap VLANs in Lab 

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#1716]
## Description

We have had some AirGap VLANs that should be blocking outbound traffic.

## How To Test

1. Have a harvester cluster set up (any nodes)
2. Have a VM running in each of these VLANs:
    a. 2011
    b. 2012
    c. 2015
    d.  2016
    e. 2017
    f. 2021
3. Use a pre-built QCOW2 Image, with something like Packer as we need a VM with (qemu-guest-agent) and additionally any other packages aready set up, as this VM will be deployed into AirGap Networks, so outbound communication should not succeed:
  a. 2013
  b. 2014
4. Ensure the VMs in 2013 & 2014 can not make outbound traffic eg: (shouldn't ping 8.8.8.8, shouldn't curl/wget an ubuntu cloud image, shouldn't communicate to an ntp server) 
5. Ensure the VMs in 2013 & 2014, can ping / download a file from 2011, 2012, 2015, 2016, 2017, 2021 VMs
6. Update Confluence Page & Close Out: https://github.com/rancherlabs/harvester-access-lab/issues/4

**Comment by khushboo-rancher** [comment]
It should be in QA sprint not QA task. :D  
I'll remove the QA tasks project to eliminate the confuse.

**Comment by irishgordo** [comment]
@khushboo-rancher thanks for correcting that :smile:

**Comment by irishgordo** [comment]
2021, is operating as expected :smile: - I'll go ahead and close this out :+1: 
Thanks @ibrokethecloud :smile:
