### ISSUE TITLE
[TEST] Scaffold Test Infrastructure For Testing Upgrades 

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#407]
## What's the test to develop? 

We should scaffold some automation for testing front-end and backend upgrades.
With:
https://github.com/harvester/harvester/issues/2387
For instance, there is now a UI Panel displayed when upgrading that offers information like:
```
WARNING:

Before you upgrade to the newer Harvester version, you must perform the required pre-upgrade checks for your cluster. Complete only those tasks that apply to your environment.

Failure to perform these checks may result in a failed upgrade or hitting known issues that require a manual workaround fix.

For more details about the release notes, please visit - More Info
```
With links to: 
- https://docs.harvesterhci.io/v1.0/upgrade/automatic/
- https://github.com/harvester/harvester/releases

For accessibility, we may want to just focus first on getting a front-end test out to validate the 'upgrade' screen does show with that information and the most recent version as a version to upgrade - or possibly making backend calls to create a spec like (maybe mock a temporary one?):
```
curl -k https://releases.rancher.com/harvester/v1.0.1/version.yaml -o new_version_upgrade.yaml
```
And applying that to the running cluster so that the `upgrade` prompt in the UI will show, to simulate a 'new' upgrade.

**Comment by khushboo-rancher** [comment]
Not applicable
