### ISSUE TITLE
[TEST] Add an option in the Jenkins job 'harvester-runtests' to run only specific test.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#451]
## What's the test to develop? Please describe

Currently, there is an option to run subset of test in the job 'harvester-runtests', user can't run a specific test. Add a param in the jenkins job which accepts test name to run.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Add an option in the Jenkins job ''harvester-runtests' to run only specific test.

**Comment by lanfon72** [comment]
Close as this has been done on Jenkins with the parameter:

![image](https://user-images.githubusercontent.com/5169694/186469305-25973298-c713-4de5-a985-bda536f2a8f1.png)
