### ISSUE TITLE
[EPIC][TEST] Implement harvester/tests Repo On ci.harvesterhci.io For #2096 To Allow For Testing

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#456]
## What's the current flow for the ci.harvesterhci.io:
Currently, ci.harvesterhci.io provisions based on the harvester/ipxe-examples repo:
- N # of Harvester Nodes
With its only validation being [the harvester-dashboard ui is accessible](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/ansible/boot_harvester_node.yml#L20-L29)
- There are no testing phases that actually implement any tests whatsoever based around our tests repo

## What are the goals for the ci.harvesterhci.io:
- To allow Jenkins to run air-gapped based tests:
    - originally the intent was purely for Harvester but it now encompasses a Rancher single instance to provide on the fly air-gapped integration testing

## The items involved:
- Dockerizing the harvester/tests repo, as it would most likely be the approach to have a Dockerfile that bundled up the tests repo and then various stages in the Jenkins pipeline could actually be triggered to run different subsets of tests
- Jenkins:
    - we are currently over a year behind in much-needed LTS releases for Jenkins since the site is publicly facing, 2.303.1 was released in: 2021-08-25, the latest version of LTS Jenkins is 2.346.3, which was released 2022-08-10, planning the upgrade path and mitigation of issues we can leverage the 'support' plugin for Jenkins to download a Dockerfile that would contain all the information about the current loadout and cross-reference upgrading to one version at a time https://www.jenkins.io/doc/upgrade-guide/
    - currently the groovy script located: https://github.com/harvester/tests/blob/main/CI/harvester-installer/roles/jenkins/templates/harvester_vagrant_installation_test.groovy.j2 - has no way of if it is "updated" being automatically deployed, thus making edits to the pipeline require someone to have access to admin to the box and update it that way:
        - offer re-build-ability, the ability to rebuild with different parameters, if there's additional tests for instance that are being set up on a feature branch to test against new harvester-installer features that are being reviewed - or implementing testing on rc based versions of Rancher for comparing integration points, etc.
        - an approach may be to try to mimic what the openstack jenkins job builder does: https://docs.openstack.org/infra/jenkins-job-builder/attic/ ,  traditionally following elements from: https://github.com/SUSE-Cloud/automation , and having a seperate git repo that would contain the jenkins job yamls- where the pipeline script can live within the harvester/installer possibly
        - another approach may be to try to continue down the jenkins job dsl based groovy way, but creating a copy of the groovy script within the harvester-installer repo, and using the job-dsl (the .groovy) being called within a separate Jenkinsfile: https://github.com/jenkinsci/job-dsl-plugin/wiki/User-Power-Moves#use-job-dsl-in-pipeline-scripts, so harvester-installer could be the sole source of pipeline edits, be able to seed the pipeline with new changes (parameters, choice options, stages etc.) then also having a job built from the seeder that would then have set stages that switch off the given PR's comment like `/run-api-tests` or `/run-integration-tests`
        - we would want Jenkins pipeline to be configured with a default testing portion, some bare minimum smoke tests to run, but allow for github pr based comments via gitops to trigger other stages running other sets of tests as desired 

## Tentative Subtasks:
- Determine Upgrade Path Compatibility to Mitigate CVE's As Well As Much-Needed Jenkins LTS Admin
- Determine Automation Of Jenkins Admin Behaviors 
- Determine Feasibility Of Implementing OpenStack Jenkins Job Builder Instead of Jenkins Job DSL Pipeline
- Determine Feasibility Of Implementing Job DSL Groovy Job Being Seeded At GitOps Comment That Also Provides All Pipeline Job Details For Running The Job As Well
- Create Dockerfile That Implements All Needed Dependencies For harvester/tests Repo
- Investigate A Way To Automate Plugin Version Maintenance and Plugin Additions
- Determine Best Way To Get Bare-Metal Node Information Funneled To Slack With Alerting On Elements Like (disk-space, cve's with packages installed, hung jobs in Jenkins, inode availability, etc.)
- Have A Testing Environment To Preform Iterations (Ideally Group Based)
~~- Determine If We Should Be Dockerizing Jenkins Instead Of Running The JAR/WAR Directly On The Nodes~~

**Comment by irishgordo** [comment]
In terms of:
> Determine If We Should Be Dockerizing Jenkins Instead Of Running The JAR/WAR Directly On The Nodes

We can not run it Dockerized, due to:
- it needing to use Docker -> https://github.com/harvester/harvester-installer/blob/master/Dockerfile.dapper -> https://github.com/harvester/harvester-installer/blob/master/Makefile that uses a Docker build wrapper ( https://github.com/rancher/dapper ) ->  that is using `luet` https://github.com/mudler/luet to build the resources

**Comment by khushboo-rancher** [comment]
Not applicable now, we are not implementing Harvester tests on ci.harvester.
