### ISSUE TITLE
[TEST] Improve the backend test framework

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#468]
## What's the test to develop? Please describe

Improve the backend test framework to make it easy for people to add new test cases. Like small and modularized fixtures, etc

**Comment by lanfon72** [comment]
# Changes
## Phase 1: Rework test cases in `apis/` by #478 
Let API test cases focus on core functionality and could be executed without dependency.

### decoupling fixtures
1. Make a Harvester API library for API calls
2. Make API test cases require minimal dependency and few fixtures
3. Make pytest's markers more clear
4. Move test cases which depends on other functionality into `Integration/`

## Phase 2: Rework test cases in `scenarios/`
Restructure `scenarios` into Integration and acceptance test cases, and let integrations could be executed with dependencies configured, without specific environment.

### Restructure `harvester_e2e_tests`
1. Separate test cases into `Integration/` and acceptance (TBD)
2. Rework test cases with dependencies
3. Rework fixtures
4. legacy code clean up

## Phase 3: Acceptance test with Robot Framework
- TBD

**Comment by khushboo-rancher** [comment]
Closing this as the framework has been improved and on going tasks are tracked separately module wise.
