### ISSUE TITLE
[DevOps BUG] Make "harvester" User Read-Only in Jenkins

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#505]
## Pre-Reqs
- the ability to have shell access to the ci.harvesterhci.io nodes

## Information
- currently in the [Harvester-Installer CI Folder README](https://github.com/harvester/harvester-installer/tree/master/ci#jenkins)
- currently in the [Harvester Tests CI Harvester-Installer Sample Settings.yml](https://github.com/harvester/tests/blob/main/CI/harvester-installer/settings.yml.sample#L11)

In both places, it is denoted that the "harvester" user should be "Read Only Access".

Yet, within:
[Authorization Strategy Global Matrix Settings for Jenkins Configuration as Code](https://github.com/harvester/tests/blob/main/CI/harvester-installer/roles/jenkins/templates/config_jenkins_as_code.yaml.j2#L14-L22)
It is outlined to have more abilities than "read-only" access.

## Roll-Out - Additional Info:
- we currently do not have an automated way to persist these changes on the Equinix nodes as:
[The Ansible Provisioning Scripts as-they-stand](https://github.com/harvester/tests/tree/main/CI/harvester-installer) do not work for provisioning infrastructure on an Ubuntu 20.04 node, which is what runs in production on the two ci.harvesterhci.io boxes.

Due to automation being broken through those scripts as-they-stand-in-this-moment in order to persist the changes to handle restart, we will manually need to implement this.

[Based around how we cary over the Configuration as Code Jenkins files](https://github.com/harvester/tests/blob/61427697cf8a63fae0f8ebfed6370af1b19baa9d/CI/harvester-installer/roles/jenkins/tasks/install_jenkins.yml#L83-L107)

We will need to either:
- manually scp a file over to the main-node of [Jenkins Configuration as Code YAML but excluding the Jijna2 Templating](https://github.com/harvester/tests/blob/main/CI/harvester-installer/roles/jenkins/templates/config_jenkins_as_code.yaml.j2)
- manually edit `/var/lib/jenkins/casc_configs/config_jenkins_as_code.yaml` with the appropriate [Matrix Based Authorization Strateg6y for "harvester" user](https://www.jenkins.io/doc/book/security/managing-security/)

We would want however to determine what the appropriate Matrix Based Authorization Strategy is for that User as the common denominator between the two options.

## Pre-Roll-Out
- we will want to create changes on this repo to [jenkins_configuration_as_code_yaml](https://github.com/harvester/tests/blob/main/CI/harvester-installer/roles/jenkins/templates/config_jenkins_as_code.yaml.j2)
to better persist the changes locally here.

**Comment by irishgordo** [comment]
### Rollout Strategy Selected (based on conversations):
- we will log in as Admin to our Jenkins instance to navigate to the Manage Jenkins -> Configure Global Security, taking a screenshot of the "initial" pre-rollout permissions for the Matrix Authorization
- we will shell directly into the Jenkins controller node
- we will create a backup of: `/var/lib/jenkins/casc_configs/config_jenkins_as_code.yaml` to `/var/lib/jenkins/casc_configs/config_jenkins_as_code.yaml.old_september_13_2022.bak`
- we will launch the editor for that file `vim` to ensure this block looks like:
```
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Read:harvester"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:harvester"
```
(NOTE: the {{}} brackets are removed, since we are editing a 'pure' yaml non-jinja2 based file in production)
- we will persist that file saved
- we will then end our shell session on the node to minimize production impact via manually shelling into production nodes
- we will then send a message out to respective comms channels letting them know of an outage, who to reach and an estimated outage time
- we will then navigate to our jenkins-ci url, then appending the uri/url with a `/safeRestart` to take advantage of the restart built into the Jenkins GUI as singed on as administrator
- we will then wait for Jenkins restart to complete
- once restart is complete, we will update the message/thread in our respective comms channels letting them know the Jenkins outage is complete
- we will then log back in as Admin and take a "post-rollout" screenshot of the Manage Jenkins -> Configure Global Security, Matrix Authorization permissions to validate that they are set in accordance with what has been determined as a team to reenforce the README: https://github.com/harvester/tests/blob/main/CI/harvester-installer/settings.yml.sample#L11 ('harvester' user only having read access to the jobs)
- we will be keeping the '

Then pending screenshot final validation we will be able to close this out as the manual change in production will have persisted.


SHOULD THERE BE ISSUES:
- we would rollback the changes, renaming the file, restarting Jenkins and mentioning out in comms channels that there will be an outage again to rollback changes.

We can, also if there are issues, provide a:
- Root Cause Analysis of what took place and why the outage occurred, prior to re-trying to implement the change

**Comment by khushboo-rancher** [comment]
Can we close this issue?

**Comment by irishgordo** [comment]
@khushboo-rancher updated :smile: 

Since, this has been manually implemented in production.
