### ISSUE TITLE
[Task] Set up an airgapped env in our testing lab

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#614]
## What's the test to develop? Please describe

We want to set up an air-gapped env similar to customer's env in our testing lab as below.

Airgapped Rancher and Airgapped Harvester where I can use Harvester for creating guest clusters.

## Harvester Setup

- 4 nodes
    - 3 master
    - 1 worker
    - PXE boot/deploy via one time boot interface in lights out management system
        - This might be able to be done via Tinkerbell
        - Setups are going to be injected via kernel arguments in seeder

## Rancher Setup

- 1 harvester node
    - RKE deploy of Ubuntu/Opensuse
    - User is using 5 nodes
        - 3 master
        - 2 worker
    - external load balancer
        - pointing at static IPs
    - private registry
        - Possibly with multiple versions

## Network setup

- DNS server
    - This is going to be required for both the private registry and for the load balancer and helm install of Rancher
- 2 VLANs
    - One VLAN with DHCP and egress
    - One VLAN with DHCP and no egress
        - This network needs part of the subnet not on DHCP for static IP assignment of Harvester nodes, Rancher nodes, and the load balancer
    - We need 4 ethernet cables going into switches that are available to host OS
        - Ideally all of these ports are going to be trunked to both VLANs (this means that the physical port on the switch has access to both VLANs), otherwise we're going to need to keep track of which NIC goes to which VLAN
        - One of the easiest ways of testing this is going to be adding in single NICs that have multiple ports (maybe 4 ports)
- Static IPs for everything
    - 4 for Harvester
    - N for however many rancher nodes
    - 1 more for the load balancer

**Comment by irishgordo** [comment]
#### Questions:
- Should we be considering running a custom DNS server (that also helps with hostname resolution) that both the Harvester & Rancher Setup can leverage?
    - one hurdle with ipxe-vagrant is the current needed manipulation of etc/hosts file, which is a snag
    - being able to have an entry for the private registry on the nameserver could be useful
    - since Rancher leverages CoreDNS, we could add the custom DNS server as an [upstream-provider](https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#coredns-upstream-nameservers) (which I think 'should' work) additionally at the Harvester level, it could be a kernel argument or in the config-create/join yaml.
    - Rancher in production systems, I feel is often leveraging a k8s underlying cluster, and us needing to provide a `--hostname=abcdefg.localdomain` is needed for a `helm` based install - `helm` and leveraging the helm charts even allowing `--devel` (to access "rc" versions of rancher) may be the best tool
- Where does the iPXE server live?  Would we want it to live/be-housed on the other Harvester node

**Comment by irishgordo** [comment]
I wanted to also mention that we will need some sort of file-server that is accessible to us for all airgaped nodes so that we can preform upgrade testing by possibly scp'ing artifacts from one location to another + version.yaml

**Comment by irishgordo** [comment]
We will also want something like MiniIO to do S3 based backups, for backing up vms before upgrade as well.

**Comment by khushboo-rancher** [comment]
Closing this in favor of Airgap automation which is in progress.
