### ISSUE TITLE
[TEST] Implement a new pipeline for upgrade testing for Jenkins

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#620]
## What's the test to develop? Please describe

Develop the upgrade tests.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Come up with the test plan
       - Install a previous version of Harvester.
       - Create some data like, VMs, volumes, Images, Backups etc.
       - Create a storageClass and use it to create a vm.
       - Prepare for the upgrade, like stopping the VMs. etc.
       - Upgrade the version of Harvester.
       - Verify the mandatory checks like CRDS, settings etc
       - Verify the VMs starting up, restore the VM/Volumes etc
       - Clean up the data.
       - Run the other backend tests.
- [x] Implement the test
- [ ] Implement the Jenkins pipeline to run this everyday.

**Comment by chrisho** [comment]
Here are some cases of customer: https://github.com/harvester/tests/issues/642#issuecomment-1333361722.

**Comment by khushboo-rancher** [comment]
1. The Harvester version destination and target versions should be configurable.
2. For upgrade. we'll need to consider getting the version details as per https://github.com/harvester/tests/issues/257
3. Need to consider verifying the transient status when the upgrade is in progress. - https://github.com/harvester/tests/issues/224 
4. To make sure the after the upgrade, all the components like os, crds, kubevirt etc are upgraded, we'll need to configurable fields in Jenkins and by default it should come from some defined location.
