### ISSUE TITLE
[TEST] Set up Jenkins server for upgrade automation test.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#647]
## What's the test to develop? Please describe

A jenkins server is needed to implement the upgrade automation test so that Jenkins can trigger the upgrade test daily.
The details are https://github.com/harvester/tests/issues/620

**Comment by masteryyh** [comment]
Currently switching from distributed architecture on Kubernetes to plain old docker container just like others, should be completed by 12/09/22.
