### ISSUE TITLE
[TEST]  Run daily test pipeline on v1.1 branch

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#718]
## What's the test to develop? Please describe

Establish a new pipeline to run the test on v1.1 branch on Jenkins daily.

**Comment by lanfon72** [comment]
Daily testing temporarily be changed to test on `v1.1-head`.

We will need some discuss (after `v1.1.2` released) to determine the solution.

**Comment by khushboo-rancher** [comment]
As discussed with @lanfon72, below points to be considered while implementing this.
1. Consider ECM lab resources to run the tests.
2. Creating a new pipeline to run daily test with seeder.
3. Migrating the existing one to seeder integrated one.

We can work on this after 1.2.0 release.

**Comment by lanfon72** [comment]
Close as multiple daily testing has been implemented, and merge machines need further discussion.

To migrate existing Jenkins to seeder, we would need dedicate machines first.
