### ISSUE TITLE
[TEST] Add test case for creating PVC in RKE2 cluster

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#748]
## What's the test to develop? Please describe

https://github.com/harvester/harvester/issues/3647

## Prerequisite and dependency of test

Any prerequisite environment and pre-condition required for this test. 
Provide test case dependency here if any.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Write the test skeleton
- [ ] Implement the test of creating PVC in RKE2 cluster
- [ ] Observe the test result on daily running test pipeline

## Additional context

Add any other context or screenshots about the test request here.

**Comment by lanfon72** [comment]
@khushboo-rancher it looks the referenced issue #737 is targeting on different case?

**Comment by khushboo-rancher** [comment]
Sorry, updated the referenced issue.
