### ISSUE TITLE
[TEST] Find the solution to run RKE1 and RKE2 test cases on daily test run

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#784]
## What's the test to develop? Please describe

As of now, we have rke2 integration test running on our CI. Based on our current infra set up we can't run both, we'll need to change the `harvester-baremetal-ansible`  in order to run the RKE1 and RKE2 both test.

**Comment by khushboo-rancher** [comment]
https://github.com/harvester/tests/pull/667#issuecomment-1375206921

**Comment by lanfon72** [comment]
fixed in https://github.com/harvester/tests/pull/793
