### ISSUE TITLE
[TEST] Need configurations on Jenkins to run RKE1 & RKE2 integration test with particular versions

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#794]
## What's the test to develop? Please describe

Need to have below configurations to select the rancher integration test version

- [ ] Run RKE1 integration test
      Version  - 
- [ ] Run RKE2 integration test
     Version -

**Comment by lanfon72** [comment]
Could you explain this request in further, is asking to make Jenkins' jobs able to propagate versions into `config.yml`, or just add particular versions for specific Harvester version when run tests?

**Comment by khushboo-rancher** [comment]
This has been done.
