### ISSUE TITLE
[Test] More than 1000 backups in the nfs backupstore in test env

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#872]
## What's the test to develop? Please describe

Currently, we have more than 1000 backups in the nfs backupstore we are using for our test. Ideally, our test should cleanup the backups once the related tests pass. 

Tasks todo:
1. Clean up the backupstore with unnecessary backups
2. Add cleaning up of backups when the related tests pass.

**Comment by albinsun** [comment]
Work log

## Investigation
1. How many file will be generated in single backuprestore?
2. Are there still files after delete a backup?

## Note
1. Delete backup TC teardown is supported recently, see [commit](https://github.com/albinsun/tests/commit/b69e167838ef45fae038935012c365ebbbde03e3). So current redundant backups should be leave from previous test run. Need to manual handle.

**Comment by albinsun** [comment]
We can found that, based on current TC, after teardown
1. Data directories `backups` and `blocks` under `pvc-<uuid>` will be deleted.
2. Metadata `volume.cfg` is left.

So current status of Tasks todo :
1. Clean up the backupstore with unnecessary backups (**TODO**, Need to manual handle)
1. Add cleaning up of backups when the related tests pass. (**DONE** by [commit](https://github.com/albinsun/tests/commit/b69e167838ef45fae038935012c365ebbbde03e3))

```
# tree -L 6 volume-nfs
├── backupstore
│   └── volumes
│       └── 42
│           └── d6
│               └── pvc-060e6b00-4ee0-4d06-9505-915bfa783d8a
│                   └── backups     <- Data
│                   └── blocks      <- Data
│                   └── volume.cfg  <- Metadata

# cat volume-nfs/backupstore/volumes/42/d6/pvc-060e6b00-4ee0-4d06-9505-915bfa783d8a/volume.cfg 
{"Name":"pvc-060e6b00-4ee0-4d06-9505-915bfa783d8a","Size":"10737418240","Labels":{"KubernetesStatus":"{\"pvName\":\"pvc-060e6b00-4ee0-4d06-9505-915bfa783d8a\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"0956108180-15h48m47s050479-09-04-disk-0\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"virt-launcher-0956108180-15h48m47s050479-09-04-z9b7p\",\"podStatus\":\"Running\",\"workloadName\":\"0956108180-15h48m47s050479-09-04\",\"workloadType\":\"VirtualMachineInstance\"}],\"lastPodRefAt\":\"\"}","VolumeRecurringJobInfo":"{}","longhorn.io/volume-access-mode":"rwx"},"CreatedTime":"2023-09-04T07:52:41Z","LastBackupName":"","LastBackupAt":"","BlockCount":"0","BackingImageName":"\"default-image-15h48m47s050479-09-04\"","BackingImageChecksum":"\"d6874371bab52c1a2049ecf9ddcf44cd66f42c2ccc17566f54674129f2c0165ceb26003f01e0d077be791405846c69d2e3a5883de7403eeb70a45b18ce902c46\""}
```

## Example
### NFS
#### Backup
![image](https://github.com/harvester/tests/assets/2773781/ce46ed06-df98-4194-a5cf-71c7b144b218)
#### Delete Backup
![image](https://github.com/harvester/tests/assets/2773781/713baf4d-e273-4519-9639-58018c3d7a7d)

### S3
#### Backup
![image](https://github.com/harvester/tests/assets/2773781/50079a56-265c-49d8-83ee-4762d8cae314)
#### Delete Backup
![image](https://github.com/harvester/tests/assets/2773781/6360192c-47d5-4965-abe5-38fdf94f7f88)

**Comment by albinsun** [comment]
Test w/ Longhorn status

leap154 has 1 vol
leap154a has 1 vol
leap154b has 2 vols
![image](https://github.com/harvester/tests/assets/2773781/d68ae2de-e793-49cd-bf18-72de99f9989b)

delete leap154
![Uploading image.png…]()

**Comment by albinsun** [comment]
Survey test

## Purpose
Check wheather current TCs has backup cleanup on Longhorn.

## Summary
Current TC teardown only handle backup record but not
1. Backup record is cleaned in teardown
2. PVC record on Longhorn and volume.cfg on Storage 

## Detail
```
<Package integration>
  <Module test_backup_restore.py>
    <Class TestBackupRestore>
      <Function test_connection[NFS]>
      <Function tests_backup_vm[NFS]>
      <Function test_restore_with_new_vm[NFS]>
      <Function test_restore_replace_and_delete_vols[NFS]>
    <Class TestMultipleBackupRestore>
      <Function test_backup_multiple[NFS]>
      <Function test_delete_first_backup[NFS]>
      <Function test_delete_last_backup[NFS]>
      <Function test_delete_middle_backup[NFS]>
```
### Before TC
![image](https://github.com/harvester/tests/assets/2773781/2481bb38-f831-4826-be44-6e2c532b470e)

### After TC
![image](https://github.com/harvester/tests/assets/2773781/c39419af-1858-4454-84c2-75ff6c626e29)

**Comment by albinsun** [comment]
Longhorn backup volumes can be query from `v1/harvester/longhorn.io.backupvolumes`
![image](https://github.com/harvester/tests/assets/2773781/4638e35d-9802-47ea-889c-fc1b156680a9)

**Comment by albinsun** [comment]
Delete API works!

Before delete pvc-08bcf7b5-7327-4886-9378-4c50b9734821
![image](https://github.com/harvester/tests/assets/2773781/2e90b2b5-9a8c-470b-8e1d-7d77b7bf459e)

After delete pvc-08bcf7b5-7327-4886-9378-4c50b9734821
![image](https://github.com/harvester/tests/assets/2773781/858eba94-978a-4b2f-9b87-184a68fbc5db)

**Comment by khushboo-rancher** [comment]
This is merged. Thanks @albinsun
