### ISSUE TITLE
[TC] Delete a volume which is in use

### ISSUE THREAD

**Issue by albinsun** [harvester/tests#905]
Delete a volume which is in use.

Ref. https://github.com/harvester/tests/issues/635

**Comment by lanfon72** [comment]
is this duplicated with #635 ?

**Comment by albinsun** [comment]
> is this duplicated with #635 ?

Hi @khushboo-rancher ,
Are these 2 TCs overlap #635 ?

**Comment by khushboo-rancher** [comment]
That's okay, @noahgildersleeve is busy with some priority work, it is okay take these up. Thanks @albinsun

**Comment by albinsun** [comment]
Daily test #691 passed 
![image](https://github.com/harvester/tests/assets/2773781/a13bdd85-f126-43ca-b02c-7b8664ef22f1)
