### ISSUE TITLE
[FAILED-TEST] Test fails on automation for TestVMOperations::test_abort_migrate

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/tests#956]
Test is failing during daily e2e on main branch for `harvester_e2e_tests/integration/test_vm_functions.py::TestVMOperations::test_abort_migrate`. The failure is `AssertionError: Failed to abort VM(vm-09h03m43s525643-10-08)'s migration, stuck on Aborting migration`.

This isn't currently happening on v1.2, and I'm queuing a new build/test for v1.2.1-rc1. We can see if this reproduces again and if it's on the release branch.

I'm attaching the test results from both a main build and the v1.2 build.

[v1-2-TestReport.zip](https://github.com/harvester/tests/files/12849198/v1-2-TestReport.zip)
[master-TestReport.zip](https://github.com/harvester/tests/files/12849199/master-TestReport.zip)

**Comment by khushboo-rancher** [comment]
@lanfon72 Could you please take a look whenever get a chance?

**Comment by lanfon72** [comment]
Close as this not happen in recent 3 runs (`harvester-install-and-test-e2e-daily` builds `#808`, `#814`, `#822`)
