### ISSUE TITLE
Refactor rancher_integration suite

### ISSUE THREAD

**Issue by albinsun** [harvester/tests#960]
- [ ] Refactor cluster_network/vm_network checker.
      https://github.com/harvester/tests/pull/949#discussion_r1348254880
- [ ] Refactor `ChartSpec` by `create_data`.
       https://github.com/harvester/tests/pull/995#discussion_r1415817175

**Comment by khushboo-rancher** [comment]
@albinsun I think, this is okay to close?

**Comment by albinsun** [comment]
all work items done, close it.
