### ISSUE TITLE
[TEST] Move the daily e2e test run on ECM lab

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#970]
## What's the test to develop? Please describe

Move the daily e2e test run on ECM lab

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Provisioning harvester cluster using seeder.
- [x] Update the corresponding Jenkins job  to trigger the e2e test on the cluster.
- [ ] harvester/harvester-baremetal-ansible#17

Related items

- [ ] Drop config/files about python 3.6 as it deprecated already.
      e.g. [py36_pytest.ini](https://github.com/harvester/tests/pull/993/files#diff-63895fc437abb610852330100574c644977cb1a88c18f6c1af90b48db2abf0ba)

**Comment by lanfon72** [comment]
close as Jenkins has deployed on ECM lab, dynamically Rancher provisioning would need add pipeline so we would track it in https://github.com/harvester/harvester-baremetal-ansible/issues/17
